# This file was auto-generated by cabal2nix. Please do NOT edit manually!

#{ cabal, SDL2, SDL2_image,fetchgit,hsSDL2 ? null }:
#{ haskellPackages ? (import <nixpkgs> {}).haskellPackages }:
{ cabal,fetchgit,SDL2,SDL2_image,hsSDL2 }:

cabal.mkDerivation (self: {
  inherit hsSDL2;
  src = fetchgit {
    url = https://github.com/jdeseno/hs-sdl2-image.git;
    rev = "1a7ef66baf96455411433898acab3589f1c4d73d";
    sha256 = "1d1x2p3jq0j1qvjahp70aykq0fr2mr3s3scgnm321wfk2j2qwvrz";
  };
  pname = "hsSDL2-image";
  version = "0.1.0.0";
  buildDepends = [ hsSDL2 ];
  pkgconfigDepends = [ SDL2 SDL2_image ];
  meta = {
    description = "Support for SDL2_image library";
    license = self.stdenv.lib.licenses.publicDomain;
    platforms = self.ghc.meta.platforms;
  };
})
