# This file was auto-generated by cabal2nix. Please do NOT edit manually!

#{ cabal, SDL2, SDL2_image,fetchgit,hsSDL2 ? null }:
#{ haskellPackages ? (import <nixpkgs> {}).haskellPackages }:
{ cabal,fetchgit,SDL2,SDL2_ttf,hsSDL2 }:

cabal.mkDerivation (self: {
  src = fetchgit {
    url = https://github.com/osa1/hsSDL2-ttf.git;
    rev = "ad617b5f81b8fff28b20ee7cfc7b1596591618bf";
    sha256 = "06s43wjdznxnz2m4mwmk4dy79q55px0hsf1lm45jzi8yd30lbvw2";
  };
  pname = "hsSDL2-ttf";
  version = "0.1.0";
  buildDepends = [ hsSDL2 ];
  pkgconfigDepends = [ SDL2 SDL2_ttf ];
  meta = {
    description = "Support for SDL2_ttf library";
    license = self.stdenv.lib.licenses.publicDomain;
    platforms = self.ghc.meta.platforms;
  };
})
