# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, sdl2, SDL2, SDL2_image }:

cabal.mkDerivation (self: {
  pname = "sdl2-image";
  version = "0.1.1.0";
  sha256 = "1rxkb4fl3350vxzwvsj25a1m8s7s179anaal33kq3q3kn0jfa72i";
  buildDepends = [ sdl2 ];
  extraLibraries = [ SDL2 ];
  pkgconfigDepends = [ SDL2 SDL2_image ];
  meta = {
    description = "Haskell binding to sdl2-image";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
