# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal,fetchgit,classyPrelude,clock,filepath,lens,liftedBase,linear,monadLoops,mtl,parsec,resourcet,hsSDL2,hsSDL2-image,hsSDL2-ttf }:

cabal.mkDerivation (self: {
  inherit hsSDL2;
  src = fetchgit {
    url = https://github.com/pmiddend/wrench;
    rev = "2899cfadacddff63a56792c8eef2948364b7b63f";
    sha256 = "1adxh552fbap6mj6rql4336y0n4839fc4vl26pkzdr7p554wf16l";
  };
  pname = "wrench";
  version = "0.1.0.0";
  buildDepends = [ classyPrelude clock filepath lens liftedBase linear monadLoops mtl parsec resourcet hsSDL2 hsSDL2-image hsSDL2-ttf ];
  meta = {
    description = "A small 2D graphics frontend similar to gloss";
    license = self.stdenv.lib.licenses.gpl3;
    platforms = self.ghc.meta.platforms;
  };
})
