# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal,fetchgit,classyPrelude,clock,filepath,lens,liftedBase,linear,monadLoops,mtl,parsec,resourcet,hsSDL2,hsSDL2-image,hsSDL2-ttf }:

cabal.mkDerivation (self: {
  inherit hsSDL2;
  src = fetchgit {
    url = https://github.com/pmiddend/wrench;
    rev = "e6d3770e093cba606b5d26f6693b998566a746f5";
    sha256 = "1i01hhi23vxhm4gjj2qkxxvxwlmxw20kwlx652na3v562nsqk8nw";
  };
  pname = "wrench";
  version = "0.1.0.0";
  buildDepends = [ classyPrelude clock filepath lens liftedBase linear monadLoops mtl parsec resourcet hsSDL2 hsSDL2-image hsSDL2-ttf ];
  meta = {
    description = "A small 2D graphics frontend similar to gloss";
    license = self.stdenv.lib.licenses.gpl3;
    platforms = self.ghc.meta.platforms;
  };
})
