# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, Cabal, QuickCheck, tasty, tastyHunit, tastyQuickcheck
, text, xmlTypes
}:

cabal.mkDerivation (self: {
  pname = "xml-picklers";
  version = "0.3.6";
  sha256 = "196iy4z58x58bjk5jy4fpmn8zhiramlyca4rd732i8j3jp6h5f6i";
  buildDepends = [ text xmlTypes ];
  testDepends = [
    Cabal QuickCheck tasty tastyHunit tastyQuickcheck text xmlTypes
  ];
  meta = {
    description = "XML picklers based on xml-types, ported from hexpat-pickle";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
